### ISSUE TITLE
try_dummy not implemented

### ISSUE THREAD

**Issue by Dextyerz** [py2many/py2many#646] opened 2024-09-18 11:50 UTC
py2many.exceptions.AstNotImplementedError: try_dummy not implemented

I got this error how to fix that

**Comment by adsharma** [comment] 2024-09-19 02:15
What language were you translating to? The error is coming from [here](https://github.com/py2many/py2many/blob/main/py2many/clike.py#L656).

Many languages subclass clike.py and override various `visit_*` methods. Your target language probably hasn't implemented support for `visit_Try`

**Comment by Dextyerz** [comment] 2024-09-21 17:41
> What language were you translating to? The error is coming from [here](https://github.com/py2many/py2many/blob/main/py2many/clike.py#L656).
> 
> Many languages subclass clike.py and override various `visit_*` methods. Your target language probably hasn't implemented support for `visit_Try`

Rust i want to translate my python to rust

**Comment by Dextyerz** [comment] 2024-09-21 17:43
Can i use try and except in python code? is it already implemented?

**Comment by adsharma** [comment] 2024-09-22 03:35
Think of it as a 2 dimensional matrix:

```
             try/except    enums    stdlib calls ....
Rust
C++
Go
mojo
...
```

Not every language supports every feature. I'd bet that Rust has the most coverage because of the history of this repo.

```
[ ~/src/py2many ] $ grep visit_Try */transpiler.py -l
pycpp/transpiler.py
pyd/transpiler.py
pydart/transpiler.py
pyjl/transpiler.py
pyv/transpiler.py
```

is a good way to check. These five languages support it. The rest need work.

**Comment by KRRT7** [comment] 2024-10-30 23:56
Hi! I've encountered this error. I have written a minimal reproducer as well.
MRE
```py
from pathlib import Path

import pickle

if __name__ == "__main__":
    dummy_file = Path("dummy_pickle_file")

    with dummy_file.open("wb") as file:
        file.write(pickle.dumps("Hello, World!"))

    with dummy_file.open("rb") as file:
        while file:
            len_next_bytes = file.read(4)
            if not len_next_bytes:
                break
            len_next = int.from_bytes(len_next_bytes, byteorder="big")
            encoded_test_name = file.read(len_next).decode("ascii")
            duration_bytes = file.read(8)
            duration = int.from_bytes(duration_bytes, byteorder="big")
            len_next_bytes = file.read(4)
            if not len_next_bytes:
                break
            len_next = int.from_bytes(len_next_bytes, byteorder="big")
            try:
                test_pickle_bin = file.read(len_next)
            except Exception as e:
                raise e from None
```

traceback:
```py
py2many --rust=1 --extension MRE.py
Writing to: .
MRE.py ... MRE.rs
MRE.py:24:12: py2many.exceptions.AstNotImplementedError: try_dummy not implemented
Error: ['rustfmt', '--edition=2021', 'MRE.rs'] (code: 1):
b'error: expected one of `!` or `::`, found `<eof>`\n --> /Users/krrt7/Desktop/selenium_base_optimizations/MRE.rs:1:1\n  |\n1 | FAILED\n  | ^^^^^^ expected one of `!` or `::`\n\n'b''
```

**Comment by adsharma** [comment] 2024-10-31 22:50
Thanks for the repro. What code do you want to see generated? Rust doesn't have the concept of try-catch.

One option is [try_blocks](https://doc.rust-lang.org/beta/unstable-book/language-features/try-blocks.html)

```
#![feature(try_blocks)]

let result: Result<_, std::error::Error> = try { file.read(len_next); }
```

Please make this change manually for now. If it works, I'll automate the generation.

**Comment by KRRT7** [comment] 2024-10-31 23:29
> Thanks for the repro. What code do you want to see generated? Rust doesn't have the concept of try-catch.
> 
> One option is [try_blocks](https://doc.rust-lang.org/beta/unstable-book/language-features/try-blocks.html)
> 
> ```
> #![feature(try_blocks)]
> 
> let result: Result<_, std::error::Error> = try { file.read(len_next); }
> ```
> 
> Please make this change manually for now. If it works, I'll automate the generation.

thanks for the quick reply! I'm not proficient with rust, I was mainly testing out the tool and came upon the error, I'm not sure what the right pattern would be :)

P.S doesn't the tool write out FAILURE! when there's an exception? In which case I can't implement it manually can I?

**Comment by adsharma** [comment] 2024-11-01 04:21
@KRRT7 Committed some code. Could you please pull and try again?

**Comment by KRRT7** [comment] 2024-11-01 06:34
> @KRRT7 Committed some code. Could you please pull and try again?

thanks, it works fine now, is there an example somewhere of a successful building such code into an extension module for python?

**Comment by adsharma** [comment] 2024-11-01 21:43
https://github.com/py2many/py2many/blob/main/tests/ext_cases/string_sum.py
https://github.com/py2many/py2many/blob/main/tests/ext_expected/string_sum.py

**Comment by adsharma** [comment] 2024-11-05 03:57
After reading some RFCs related to try_blocks, I found a combination that works:

```
#![feature(try_blocks)]

use std::io;
use std::io::Bytes;
use std::io::Read;
use std::fs::File;

pub fn main() {
    let result: Result<Bytes<File>, io::Error> = try {
        File::open("foo.bin")?.bytes()
    };
    //unsupported exception handler
    println!("Hello, world!: {:?}", result);
}
```

However, the hard part is inferring the type of `result`. This is the reason why the feature is not moving from unstable -> stable. The same difficulty applies to transpilers such as py2many.

**Comment by adsharma** [comment] 2024-11-08 01:50
Please reopen a new one if there are more issues. The just added `--no-strict` option may be useful to work around these type of issues.

**Closed by adsharma** 2024-11-08 01:50 UTC
